<<<<<<< HEAD
# Generated by Django 4.2.21 on 2025-05-23 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 5.2.1 on 2025-05-19 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
>>>>>>> b3e28ce36af46af1b515470ac029a08afb177ad9


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0002_chamado'),
=======
        ('App', '0002_chamado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> b3e28ce36af46af1b515470ac029a08afb177ad9
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={},
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='resolvido',
        ),
        migrations.AddField(
            model_name='chamado',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_analise', 'Em Análise'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='setor',
<<<<<<< HEAD
            field=models.CharField(choices=[('ti', 'TI'), ('rh', 'RH'), ('financeiro', 'Financeiro'), ('manutencao', 'Manutenção'), ('limpeza', 'Limpeza'), ('outros', 'Outros')], max_length=20),
=======
            field=models.CharField(choices=[('ti', 'TI'), ('rh', 'RH'), ('financeiro', 'Financeiro'), ('outros', 'Outros')], max_length=20),
>>>>>>> b3e28ce36af46af1b515470ac029a08afb177ad9
        ),
        migrations.AlterField(
            model_name='chamado',
            name='urgencia',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=10),
        ),
        migrations.CreateModel(
            name='AtualizacaoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.chamado')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
