# Generated by Django 4.2.21 on 2025-05-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='chat_room_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
