# Generated by Django 4.2.21 on 2025-05-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_chamado_chat_room_name_chatmessage_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='setor',
            field=models.CharField(choices=[('ti', 'TI'), ('rh', 'RH'), ('financeiro', 'Financeiro'), ('manutencao', 'Manutenção'), ('limpeza', 'Limpeza'), ('outros', 'Outros'), ('chat_suporte', 'Chat de Suporte')], max_length=20),
        ),
    ]
