# Generated by Django 4.2.13 on 2025-08-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_chamado_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='chat_room_name',
        ),
        migrations.AlterField(
            model_name='chamado',
            name='setor',
            field=models.CharField(choices=[('ti', 'TI'), ('rh', 'RH'), ('financeiro', 'Financeiro'), ('manutencao', 'Manutenção'), ('limpeza', 'Limpeza'), ('outros', 'Outros')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
