# Generated by Django 4.2.13 on 2025-08-15 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('setor', models.CharField(choices=[('ti', 'TI'), ('rh', 'RH'), ('financeiro', 'Financeiro'), ('manutencao', 'Manutenção'), ('limpeza', 'Limpeza'), ('outros', 'Outros')], max_length=20)),
                ('urgencia', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_analise', 'Em Análise'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'App_chamado',
            },
        ),
        migrations.CreateModel(
            name='AtualizacaoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chamados.chamado')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'App_atualizacaochamado',
            },
        ),
    ]
