# Generated by Django 4.2.13 on 2025-08-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chamados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atualizacaochamado',
            table=None,
        ),
    ]
